# Generated by Django 5.1.7 on 2025-03-13 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_avisos_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(validators=[django.core.validators.RegexValidator(message='A URL deve ser do YouTube.', regex='^https://(www\\.)?youtube\\.com/.*$')])),
                ('titulo', models.CharField(default='Assista ao vídeo!', max_length=100)),
                ('mensagem', models.CharField(default='Dúvidas? Entre em contato', max_length=100)),
            ],
        ),
    ]
