# Generated by Django 5.1.7 on 2025-03-13 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avisos',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='A URL deve ser um link válido do YouTube.', regex='^(https://)?(www\\.)?(youtube\\.com|youtu\\.be)/.*$')]),
        ),
    ]
