# Generated by Django 5.1.7 on 2025-03-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_delete_avisos_alter_video_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mensagem',
            field=models.CharField(default='Dúvidas? Entre em contato', max_length=500),
        ),
    ]
