# Generated by Django 5.1.7 on 2025-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_video_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mensagem',
            field=models.TextField(default='Dúvidas? Entre em contato'),
        ),
    ]
